- name: Install pyenv into "{{ user }}"
  include_role:
    name: markosamuli.pyenv
  vars:
    become_user: "{{ user }}"
    become: true
    pyenv_init_shell: true
    pyenv_home: "/home/{{ user }}/"
    pyenv_root: "/home/{{ user }}/.pyenv"
    pyenv_detect_existing_install: true
    pyenv_python_versions:
      - "3.6.9"
      - "3.7.8"
      - "3.8.5"
    pyenv_global: >-
      3.6.9
      3.7.8
      3.8.5
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user

- name: install poetry into "{{ user }}"
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
  args:
    creates: "/home/{{ user }}/.poetry"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user

- name: add poetry to path
  become_user: "{{ user }}"
  lineinfile:
    path: "/home/{{ user }}/.bashrc"
    regexp: "^export PATH=\\$PATH\\:\\$HOME/\\.poetry/bin"
    line: "export PATH=$PATH:$HOME/.poetry/bin"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user
